#!/bin/bash
# usage: xper_index.sh FLAG_CLEAR FLAG_ADD FLAG_REMOVE STR_VERSION_SOURCE FLAG_AFTER FLAG_BEFORE FLAG_SWAP STR_VERSION_TARGET

CLEAR=$1
ADD=$1
REMOVE=$1
VERSION_SOURCE=$1
AFTER=$1
BEFORE=$1
SWAP=$1
VERSION_TARGET=$1

# TODO
